### ISSUE TITLE
[BUG] Token generated later to same user can't work properly

### ISSUE THREAD

**Issue by hiroya8649** [riverrun/phauxth#102]
### Environment

* Elixir & Erlang/OTP versions (elixir --version): 
Erlang/OTP 20 [erts-9.3.3.3] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:10] [hipe] [kernel-poll:false]
Elixir 1.7.0 (compiled with Erlang/OTP 19)

* Operating system: 
macOS Mojave 10.14

### Current behavior
Can't access to data by the token which generated after a session has exist to the same user.
I just try build an brand new project with `mix phx.new` and `mix phauxth.new --api --confirm`.
You can try it [here](https://github.com/hiroya8649/phauxth_test).

### Expected behavior

Works normally no matter how many sessions a user have.

### Additional information
- First, create an user and you will get an confirm url with an token, said token A.
Then confirm the account and try the list users API with token A, it works.
- Second, create a new session with create session API, get a new token, said token B.
Try any API and it will report:
```
[error] #PID<0.486.0> running TestPhauxthWeb.Endpoint (connection #PID<0.485.0>, stream id 1) terminated
Server: localhost:4000 (http)
Request: GET /api/users
** (exit) an exception was raised:
    ** (FunctionClauseError) no function clause matching in TestPhauxth.Accounts.get_by/1
        (test_phauxth) lib/test_phauxth/accounts/accounts.ex:25: TestPhauxth.Accounts.get_by(%{session_id: 1})
        (phauxth) lib/phauxth/authenticate_token.ex:45: Phauxth.AuthenticateToken.get_user/2
        (phauxth) lib/phauxth/authenticate_token.ex:45: Phauxth.AuthenticateToken.call/2
        (test_phauxth) lib/test_phauxth_web/router.ex:4: TestPhauxthWeb.Router.api/2
        (test_phauxth) lib/test_phauxth_web/router.ex:1: TestPhauxthWeb.Router.__pipe_through0__/1
        (phoenix) lib/phoenix/router.ex:270: Phoenix.Router.__call__/1
        (test_phauxth) lib/test_phauxth_web/endpoint.ex:1: TestPhauxthWeb.Endpoint.plug_builder_call/2
        (test_phauxth) lib/plug/debugger.ex:122: TestPhauxthWeb.Endpoint."call (overridable 3)"/2
        (test_phauxth) lib/test_phauxth_web/endpoint.ex:1: TestPhauxthWeb.Endpoint.call/2
        (phoenix) lib/phoenix/endpoint/cowboy2_handler.ex:34: Phoenix.Endpoint.Cowboy2Handler.init/2
        (cowboy) /Users/roy_chang/Projects/test_phauxth/deps/cowboy/src/cowboy_handler.erl:41: :cowboy_handler.execute/2
        (cowboy) /Users/roy_chang/Projects/test_phauxth/deps/cowboy/src/cowboy_stream_h.erl:296: :cowboy_stream_h.execute/3
        (cowboy) /Users/roy_chang/Projects/test_phauxth/deps/cowboy/src/cowboy_stream_h.erl:274: :cowboy_stream_h.request_process/3
        (stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3
```
And you can try with token A it just works fine.
Try `TestPhauxth.Accounts.get_by(%{session_id: 1})` directly in `iex`, it raised:
```
** (FunctionClauseError) no function clause matching in TestPhauxth.Accounts.get_by/1    
    
    The following arguments were given to TestPhauxth.Accounts.get_by/1:
    
        # 1
        %{session_id: 1}
    
    Attempted function clauses (showing 3 out of 3):
    
        def get_by(%{"session_id" => session_id})
        def get_by(%{"email" => email})
        def get_by(%{"user_id" => user_id})
    
    (test_phauxth) lib/test_phauxth/accounts/accounts.ex:25: TestPhauxth.Accounts.get_by/1
```

It seems to be easy to solve(just modify the `get_by` function in `Accounts`), but I'm not sure is there any wrong in Phauxth library, I have tried to read the code in library but I didn't find anything weird.
And this didn't happen in todoapp example.

**Comment by riverrun** [comment]
The error you are getting is because the token is signed with a map with atom keys, but the `get_by` function clauses are using maps with string keys.

**Comment by riverrun** [comment]
I have updated the installer with changes to the `Token.sign` call. Can you try that and let me know if there are any existing issues?

**Comment by hiroya8649** [comment]
@riverrun I have try with the newest 2.0.0 installer and it works fine, thanks for your quick fix!
