### ISSUE TITLE
seeds.exs from wiki

### ISSUE THREAD

**Issue by nordbit** [riverrun/phauxth#107]
### Environment

* Elixir & Erlang/OTP versions (elixir --version): 
* Operating system: 

### Issue

```Edit the priv/repo/seeds.exs file. This file contains an example of how to create user(s) at this stage.```
I don't see any example in my seeds.exs - untouched from original phx.new, Phauxth installer do not modify seeds.exs

**Comment by nordbit** [comment]
Ok, I found lost file - generator put seeds.ex under hellopriv not hello/priv

**Comment by riverrun** [comment]
Ok. I'll check the generator. It shouldn't be putting the seeds there.

**Comment by riverrun** [comment]
I just fixed this issue. The seeds.exs file are now being put in the correct place.

Thanks for reporting the issue.
