### ISSUE TITLE
[FEATURE] Allow specifying domain for remember cookie

### ISSUE THREAD

**Issue by dfalling** [riverrun/phauxth#110]
### Problem

My API is at `api.mydomain.com`, while my UI is at `www.mydomain.com`.  I'm configuring Phoenix to use `mydomain.com` for the session cookie in my Session.Plug, but don't see a way to configure it for my remember cookie.

### Solution

Add `domain` to the `add_rem_cookie` function.  It's getting pretty long already, so maybe a keyword list for the args?  Alternatively it could be added to the Remember plug.

**Comment by riverrun** [comment]
I will look into this in the new year - I am busy until then.

**Comment by riverrun** [comment]
I just uploaded a `rem_cookie_options` branch, and on that branch, I have added a `domain` option to `add_rem_cookie`. Could you try that and let me know if it solves this issue?

**Comment by dfalling** [comment]
Yes, that's exactly what I needed!  Thanks!

**Comment by riverrun** [comment]
Version 2.3.1 has these changes.
