### ISSUE TITLE
[FEATURE] Too Many Login Attempts

### ISSUE THREAD

**Issue by keslert** [riverrun/phauxth#117]
### Problem

Many applications limit failed login attempts by ip address and username.

### Solution

I imagine this would happen in the session_controller using the result of Login.verify to store failed attempts in a "failed_attempts" table. Also before calling Login.verify, you'd have a preliminary call to Login.rate_limited?(email, ip_address). 

Does this seem like a valid approach? Is there a more accepted approach?

**Comment by riverrun** [comment]
First of all, this issue (rate limiting) is beyond the scope of this authentication library. However, I have implemented rate limiting for another open source library, and I can provide a link to that and other useful links.

The commit where I added rate limiting is [this one](https://github.com/vutuv/vutuv/pull/709), using the [Hammer library](https://github.com/ExHammer/hammer),  and it was in response to [this issue](https://github.com/vutuv/vutuv/issues/653).

There is another rate limiting library called [ex_rated](https://github.com/grempe/ex_rated), and [this blog post](https://blog.danielberkompas.com/2015/06/16/rate-limiting-a-phoenix-api/) can provide you with information about how you could use it in a phoenix app.

If you have any further questions, just let me know.
