### ISSUE TITLE
Wiki documentation update proposition

### ISSUE THREAD

**Issue by patatoid** [riverrun/phauxth#119]
First thanks for the repo which is a great tool to setup authentication in Elixir apps.

Just a proposition of documentation update concerning two sections :
- dependencies that are outdated in documentation
- brings more precision about steps in order to configure Phauxth

As it is not possible yet to propose pull requests for wiki pages, I created a gist [here](https://gist.github.com/patatoid/9b63c703e4db37ec2f48d7c8d6d18283)

Cheers :)

**Comment by riverrun** [comment]
Thanks for your help. I will get back to you later this week.
