### ISSUE TITLE
function Bcrypt.no_user_verify/1 is undefined (module Bcrypt is not available)

### ISSUE THREAD

**Issue by dsignr** [riverrun/phauxth#13]
I think perhaps it's a namespacing issue? Library looks really promising, thanks for the hard work and effort 👍 

```
Request: POST /sessions
** (exit) an exception was raised:
    ** (UndefinedFunctionError) function Bcrypt.no_user_verify/1 is undefined (module Bcrypt is not available)
        Bcrypt.no_user_verify([])
        (phauxth) lib/phauxth/login.ex:38: Phauxth.Login.check_pass/4
        (phauxth) lib/phauxth/login.ex:38: Phauxth.Login.verify/3
```

**Comment by riverrun** [comment]
Thanks for reporting the issue.

I'm in the middle of updating the login base module and one of the dependencies at the moment. I should be able to give you more help later today or tomorrow.

**Comment by dsignr** [comment]
That's so awesome. Thanks for your fast response and assistance.

I found your library interesting because the others I've tried are doing too many things at once (Eg. sending emails using a particular service provider) and some of them are now on the verge of re-writes. I wanted something that is small, modular and extensible, so I found your library and saw the code and immediately fell in love with its simplicity and clarity of code.

I do have a plan of testing out some things such as adding IP address as an attribute when computing the hash (I think Google does this) so that even if a user's cookies are stolen by an attacker, he still won't be able to login because his IP is different. I'll send through a PR if it works :D

**Comment by dsignr** [comment]
`{:bcrypt_elixir, "~> 0.1.0"}` adding this to my `mix.exs` solved this issue. Should I just close this issue for now? Thanks!

**Comment by riverrun** [comment]
Yes, I'll close it now. I forgot to add that to the documentation.

By the way, bcrypt_elixir is now 0.11.0, and I will be updating it to version 1.0 fairly soon.

**Comment by dsignr** [comment]
That's great! Thanks for the update :)

**Comment by dsignr** [comment]
Now (even after updating `bcrypt_elxir`), I now get this error when I try to register `/users/new`:

`function Comeonin.Bcrypt.add_hash/1 is undefined or private`.

If this should be under a new issue, please let me know :)

**Comment by riverrun** [comment]
Which version of Phauxth are you on? Can you make sure you are on 0.12.1-rc.1 and try again?

**Comment by dsignr** [comment]
Oh wow, I totally missed that .1 (rc.1). Here's my config which is working now:
```
{:phauxth, "~> 0.12-rc"},
{:comeonin, "~> 4.0-rc"},
{:bcrypt_elixir, "~> 0.11"}
```
Thanks a ton for your help :)
