### ISSUE TITLE
Default user

### ISSUE THREAD

**Issue by lachezar** [riverrun/phauxth#14]
It would be a good idea to have either a default user that is created upon installation or a mix task to create such a user. 

Right now I had to comment out the `plug Phauxth.Authenticate` in the router.ex to bypass the authentication so that I can create an account the very first time.

**Comment by riverrun** [comment]
Maybe I am misunderstanding what you want to do, but you could generate users in the `repo/seeds.exs` file. There's more info about that [here](https://hexdocs.pm/phoenix/seeding_data.html).

**Comment by lachezar** [comment]
This is more of a "nice to have" feature.

I was thinking about a quick way to generate a user with a proper password hash (something similar to [Django's admin](https://docs.djangoproject.com/en/1.11/intro/tutorial02/#creating-an-admin-user)). Otherwise you have to figure out for yourself how to compute the bcrypt password hash.

**Comment by riverrun** [comment]
I've updated the [New project](https://github.com/riverrun/phauxth/wiki/New-project) page with information about how you can create users by editing the `priv/repo/seeds.exs` file. If you have any suggestions for making this clearer, please let me know.

**Comment by lachezar** [comment]
Thanks, that should help a lot for newcomers :)

**Comment by riverrun** [comment]
Just a note to say that I've changed how I've organized this, and now the installer installs an example `priv/repo/seeds.exs` file. The New project page lets developers know that this file needs editing.
