### ISSUE TITLE
Basic 0.15 project fails tests when created with --confirm option

### ISSUE THREAD

**Issue by guidotripaldi** [riverrun/phauxth#16]
I'm trying to migrate some projects from Phx1.2/Openmaize to Phx1.3/Phauxth, so I've start to play with Phauxth 0.15, but it seems that v.015 isn't yet ready when the `--confirm` option is given, because eight tests failed with these two kinds of errors:

   `** (UndefinedFunctionError) function Phauxth.Confirm.gen_token/0 is undefined or private`
and
   `** (UndefinedFunctionError) function Phauxth.Confirm.verify/2 is undefined or private. Did you mean one of: * verify/3`

I've created a new playground project through the following steps:

new project:
  `$ mix phx.new alibaba_html_confirm && cd alibaba_html_confirm`

phauxth setup (html + confirm):
  `$ mix phauxth.new --confirm`

add following dependency to mix.ex file:
  `{:phauxth, "~> 0.15"}, {:bcrypt_elixir, "~> 0.12"}`

run usual initialization commands:
   `$ mix deps.get && mix deps.compile && mix ecto.create && mix ecto.migrate`

run tests:
   `$ mix test`

**Full transcript of the errors**:

[alibaba_html_confirm]$ mix test
...

  1) test creates user when data is valid (AlibabaHtmlConfirmWeb.UserControllerTest)
     test/alibaba_html_confirm_web/controllers/user_controller_test.exs:46
     ** (UndefinedFunctionError) function Phauxth.Confirm.gen_token/0 is undefined or private
     code: conn = post conn, user_path(conn, :create), user: @create_attrs
     stacktrace:
       (phauxth) Phauxth.Confirm.gen_token()
       (alibaba_html_confirm) lib/alibaba_html_confirm_web/controllers/user_controller.ex:21: AlibabaHtmlConfirmWeb.UserController.create/2
       (alibaba_html_confirm) lib/alibaba_html_confirm_web/controllers/user_controller.ex:1: AlibabaHtmlConfirmWeb.UserController.action/2
       (alibaba_html_confirm) lib/alibaba_html_confirm_web/controllers/user_controller.ex:1: AlibabaHtmlConfirmWeb.UserController.phoenix_controller_pipeline/2
       (alibaba_html_confirm) lib/alibaba_html_confirm_web/endpoint.ex:1: AlibabaHtmlConfirmWeb.Endpoint.instrument/4
       (phoenix) lib/phoenix/router.ex:278: Phoenix.Router.__call__/1
       (alibaba_html_confirm) lib/alibaba_html_confirm_web/endpoint.ex:1: AlibabaHtmlConfirmWeb.Endpoint.plug_builder_call/2
       (alibaba_html_confirm) lib/alibaba_html_confirm_web/endpoint.ex:1: AlibabaHtmlConfirmWeb.Endpoint.call/2
       (phoenix) lib/phoenix/test/conn_test.ex:224: Phoenix.ConnTest.dispatch/5
       test/alibaba_html_confirm_web/controllers/user_controller_test.exs:47: (test)

...

  2) test does not create user and renders errors when data is invalid (AlibabaHtmlConfirmWeb.UserControllerTest)
     test/alibaba_html_confirm_web/controllers/user_controller_test.exs:51
     ** (UndefinedFunctionError) function Phauxth.Confirm.gen_token/0 is undefined or private
     code: conn = post conn, user_path(conn, :create), user: @invalid_attrs
     stacktrace:
       (phauxth) Phauxth.Confirm.gen_token()
       (alibaba_html_confirm) lib/alibaba_html_confirm_web/controllers/user_controller.ex:21: AlibabaHtmlConfirmWeb.UserController.create/2
       (alibaba_html_confirm) lib/alibaba_html_confirm_web/controllers/user_controller.ex:1: AlibabaHtmlConfirmWeb.UserController.action/2
       (alibaba_html_confirm) lib/alibaba_html_confirm_web/controllers/user_controller.ex:1: AlibabaHtmlConfirmWeb.UserController.phoenix_controller_pipeline/2
       (alibaba_html_confirm) lib/alibaba_html_confirm_web/endpoint.ex:1: AlibabaHtmlConfirmWeb.Endpoint.instrument/4
       (phoenix) lib/phoenix/router.ex:278: Phoenix.Router.__call__/1
       (alibaba_html_confirm) lib/alibaba_html_confirm_web/endpoint.ex:1: AlibabaHtmlConfirmWeb.Endpoint.plug_builder_call/2
       (alibaba_html_confirm) lib/alibaba_html_confirm_web/endpoint.ex:1: AlibabaHtmlConfirmWeb.Endpoint.call/2
       (phoenix) lib/phoenix/test/conn_test.ex:224: Phoenix.ConnTest.dispatch/5
       test/alibaba_html_confirm_web/controllers/user_controller_test.exs:52: (test)

.......10:51:35.793 request_id=glv3c4k25r1t1j8ejak36qp7k3ldjkv2 [warn] user=nil message="invalid password"
..10:51:37.130 request_id=rcf15o9v97ip75oq6s1trs5f9kjphi6o [warn] user=nil message="account unconfirmed"
..........

  3) test confirmation fails for incorrect key (AlibabaHtmlConfirmWeb.ConfirmControllerTest)
     test/alibaba_html_confirm_web/controllers/confirm_controller_test.exs:21
     ** (UndefinedFunctionError) function Phauxth.Confirm.verify/2 is undefined or private. Did you mean one of:

           * verify/3

     code: conn = get(conn, confirm_path(conn, :new, email: email, key: key))
     stacktrace:
       (phauxth) Phauxth.Confirm.verify(%{"email" => "arthur@mail.com", "key" => "pu9-VNdgE8V9QzO19RLCG3KUNjpxuixg"}, AlibabaHtmlConfirm.Accounts)
       (alibaba_html_confirm) lib/alibaba_html_confirm_web/controllers/confirm_controller.ex:8: AlibabaHtmlConfirmWeb.ConfirmController.new/2
       (alibaba_html_confirm) lib/alibaba_html_confirm_web/controllers/confirm_controller.ex:1: AlibabaHtmlConfirmWeb.ConfirmController.action/2
       (alibaba_html_confirm) lib/alibaba_html_confirm_web/controllers/confirm_controller.ex:1: AlibabaHtmlConfirmWeb.ConfirmController.phoenix_controller_pipeline/2
       (alibaba_html_confirm) lib/alibaba_html_confirm_web/endpoint.ex:1: AlibabaHtmlConfirmWeb.Endpoint.instrument/4
       (phoenix) lib/phoenix/router.ex:278: Phoenix.Router.__call__/1
       (alibaba_html_confirm) lib/alibaba_html_confirm_web/endpoint.ex:1: AlibabaHtmlConfirmWeb.Endpoint.plug_builder_call/2
       (alibaba_html_confirm) lib/alibaba_html_confirm_web/endpoint.ex:1: AlibabaHtmlConfirmWeb.Endpoint.call/2
       (phoenix) lib/phoenix/test/conn_test.ex:224: Phoenix.ConnTest.dispatch/5
       test/alibaba_html_confirm_web/controllers/confirm_controller_test.exs:24: (test)

  4) test confirmation fails for incorrect email (AlibabaHtmlConfirmWeb.ConfirmControllerTest)
     test/alibaba_html_confirm_web/controllers/confirm_controller_test.exs:29
     ** (UndefinedFunctionError) function Phauxth.Confirm.verify/2 is undefined or private. Did you mean one of:

           * verify/3

     code: conn = get(conn, confirm_path(conn, :new, email: email, key: key))
     stacktrace:
       (phauxth) Phauxth.Confirm.verify(%{"email" => "gerald@mail.com", "key" => "pu9-VNdgE8V9qZo19rlcg3KUNjpxuixg"}, AlibabaHtmlConfirm.Accounts)
       (alibaba_html_confirm) lib/alibaba_html_confirm_web/controllers/confirm_controller.ex:8: AlibabaHtmlConfirmWeb.ConfirmController.new/2
       (alibaba_html_confirm) lib/alibaba_html_confirm_web/controllers/confirm_controller.ex:1: AlibabaHtmlConfirmWeb.ConfirmController.action/2
       (alibaba_html_confirm) lib/alibaba_html_confirm_web/controllers/confirm_controller.ex:1: AlibabaHtmlConfirmWeb.ConfirmController.phoenix_controller_pipeline/2
       (alibaba_html_confirm) lib/alibaba_html_confirm_web/endpoint.ex:1: AlibabaHtmlConfirmWeb.Endpoint.instrument/4
       (phoenix) lib/phoenix/router.ex:278: Phoenix.Router.__call__/1
       (alibaba_html_confirm) lib/alibaba_html_confirm_web/endpoint.ex:1: AlibabaHtmlConfirmWeb.Endpoint.plug_builder_call/2
       (alibaba_html_confirm) lib/alibaba_html_confirm_web/endpoint.ex:1: AlibabaHtmlConfirmWeb.Endpoint.call/2
       (phoenix) lib/phoenix/test/conn_test.ex:224: Phoenix.ConnTest.dispatch/5
       test/alibaba_html_confirm_web/controllers/confirm_controller_test.exs:32: (test)

  5) test confirmation succeeds for correct key (AlibabaHtmlConfirmWeb.ConfirmControllerTest)
     test/alibaba_html_confirm_web/controllers/confirm_controller_test.exs:13
     ** (UndefinedFunctionError) function Phauxth.Confirm.verify/2 is undefined or private. Did you mean one of:

           * verify/3

     code: conn = get(conn, confirm_path(conn, :new, email: email, key: key))
     stacktrace:
       (phauxth) Phauxth.Confirm.verify(%{"email" => "arthur@mail.com", "key" => "pu9-VNdgE8V9qZo19rlcg3KUNjpxuixg"}, AlibabaHtmlConfirm.Accounts)
       (alibaba_html_confirm) lib/alibaba_html_confirm_web/controllers/confirm_controller.ex:8: AlibabaHtmlConfirmWeb.ConfirmController.new/2
       (alibaba_html_confirm) lib/alibaba_html_confirm_web/controllers/confirm_controller.ex:1: AlibabaHtmlConfirmWeb.ConfirmController.action/2
       (alibaba_html_confirm) lib/alibaba_html_confirm_web/controllers/confirm_controller.ex:1: AlibabaHtmlConfirmWeb.ConfirmController.phoenix_controller_pipeline/2
       (alibaba_html_confirm) lib/alibaba_html_confirm_web/endpoint.ex:1: AlibabaHtmlConfirmWeb.Endpoint.instrument/4
       (phoenix) lib/phoenix/router.ex:278: Phoenix.Router.__call__/1
       (alibaba_html_confirm) lib/alibaba_html_confirm_web/endpoint.ex:1: AlibabaHtmlConfirmWeb.Endpoint.plug_builder_call/2
       (alibaba_html_confirm) lib/alibaba_html_confirm_web/endpoint.ex:1: AlibabaHtmlConfirmWeb.Endpoint.call/2
       (phoenix) lib/phoenix/test/conn_test.ex:224: Phoenix.ConnTest.dispatch/5
       test/alibaba_html_confirm_web/controllers/confirm_controller_test.exs:16: (test)

  6) test reset password fails for invalid email (AlibabaHtmlConfirmWeb.PasswordResetControllerTest)
     test/alibaba_html_confirm_web/controllers/password_reset_controller_test.exs:25
     ** (UndefinedFunctionError) function Phauxth.Confirm.gen_token/0 is undefined or private
     code: conn = post(conn, password_reset_path(conn, :create), password_reset: @invalid_email)
     stacktrace:
       (phauxth) Phauxth.Confirm.gen_token()
       (alibaba_html_confirm) lib/alibaba_html_confirm_web/controllers/password_reset_controller.ex:11: AlibabaHtmlConfirmWeb.PasswordResetController.create/2
       (alibaba_html_confirm) lib/alibaba_html_confirm_web/controllers/password_reset_controller.ex:1: AlibabaHtmlConfirmWeb.PasswordResetController.action/2
       (alibaba_html_confirm) lib/alibaba_html_confirm_web/controllers/password_reset_controller.ex:1: AlibabaHtmlConfirmWeb.PasswordResetController.phoenix_controller_pipeline/2
       (alibaba_html_confirm) lib/alibaba_html_confirm_web/endpoint.ex:1: AlibabaHtmlConfirmWeb.Endpoint.instrument/4
       (phoenix) lib/phoenix/router.ex:278: Phoenix.Router.__call__/1
       (alibaba_html_confirm) lib/alibaba_html_confirm_web/endpoint.ex:1: AlibabaHtmlConfirmWeb.Endpoint.plug_builder_call/2
       (alibaba_html_confirm) lib/alibaba_html_confirm_web/endpoint.ex:1: AlibabaHtmlConfirmWeb.Endpoint.call/2
       (phoenix) lib/phoenix/test/conn_test.ex:224: Phoenix.ConnTest.dispatch/5
       test/alibaba_html_confirm_web/controllers/password_reset_controller_test.exs:26: (test)

  7) test reset password fails for incorrect key (AlibabaHtmlConfirmWeb.PasswordResetControllerTest)
     test/alibaba_html_confirm_web/controllers/password_reset_controller_test.exs:30
     ** (UndefinedFunctionError) function Phauxth.Confirm.PassReset.verify/2 is undefined or private. Did you mean one of:

           * verify/3

     code: conn = put(conn, password_reset_path(conn, :update), password_reset: @invalid_attrs)
     stacktrace:
       (phauxth) Phauxth.Confirm.PassReset.verify(%{"email" => "gladys@mail.com", "key" => "pu9-VNDGe8v9QzO19RLCg3KUNjpxuixg", "password" => "^hEsdg*F899"}, AlibabaHtmlConfirm.Accounts)
       (alibaba_html_confirm) lib/alibaba_html_confirm_web/controllers/password_reset_controller.ex:27: AlibabaHtmlConfirmWeb.PasswordResetController.update/2
       (alibaba_html_confirm) lib/alibaba_html_confirm_web/controllers/password_reset_controller.ex:1: AlibabaHtmlConfirmWeb.PasswordResetController.action/2
       (alibaba_html_confirm) lib/alibaba_html_confirm_web/controllers/password_reset_controller.ex:1: AlibabaHtmlConfirmWeb.PasswordResetController.phoenix_controller_pipeline/2
       (alibaba_html_confirm) lib/alibaba_html_confirm_web/endpoint.ex:1: AlibabaHtmlConfirmWeb.Endpoint.instrument/4
       (phoenix) lib/phoenix/router.ex:278: Phoenix.Router.__call__/1
       (alibaba_html_confirm) lib/alibaba_html_confirm_web/endpoint.ex:1: AlibabaHtmlConfirmWeb.Endpoint.plug_builder_call/2
       (alibaba_html_confirm) lib/alibaba_html_confirm_web/endpoint.ex:1: AlibabaHtmlConfirmWeb.Endpoint.call/2
       (phoenix) lib/phoenix/test/conn_test.ex:224: Phoenix.ConnTest.dispatch/5
       test/alibaba_html_confirm_web/controllers/password_reset_controller_test.exs:31: (test)

  8) test reset password succeeds for correct key (AlibabaHtmlConfirmWeb.PasswordResetControllerTest)
     test/alibaba_html_confirm_web/controllers/password_reset_controller_test.exs:19
     ** (UndefinedFunctionError) function Phauxth.Confirm.PassReset.verify/2 is undefined or private. Did you mean one of:

           * verify/3

     code: conn = put(conn, password_reset_path(conn, :update), password_reset: @valid_attrs)
     stacktrace:
       (phauxth) Phauxth.Confirm.PassReset.verify(%{"email" => "gladys@mail.com", "key" => "pu9-VNdgE8V9qZo19rlcg3KUNjpxuixg", "password" => "^hEsdg*F899"}, AlibabaHtmlConfirm.Accounts)
       (alibaba_html_confirm) lib/alibaba_html_confirm_web/controllers/password_reset_controller.ex:27: AlibabaHtmlConfirmWeb.PasswordResetController.update/2
       (alibaba_html_confirm) lib/alibaba_html_confirm_web/controllers/password_reset_controller.ex:1: AlibabaHtmlConfirmWeb.PasswordResetController.action/2
       (alibaba_html_confirm) lib/alibaba_html_confirm_web/controllers/password_reset_controller.ex:1: AlibabaHtmlConfirmWeb.PasswordResetController.phoenix_controller_pipeline/2
       (alibaba_html_confirm) lib/alibaba_html_confirm_web/endpoint.ex:1: AlibabaHtmlConfirmWeb.Endpoint.instrument/4
       (phoenix) lib/phoenix/router.ex:278: Phoenix.Router.__call__/1
       (alibaba_html_confirm) lib/alibaba_html_confirm_web/endpoint.ex:1: AlibabaHtmlConfirmWeb.Endpoint.plug_builder_call/2
       (alibaba_html_confirm) lib/alibaba_html_confirm_web/endpoint.ex:1: AlibabaHtmlConfirmWeb.Endpoint.call/2
       (phoenix) lib/phoenix/test/conn_test.ex:224: Phoenix.ConnTest.dispatch/5
       test/alibaba_html_confirm_web/controllers/password_reset_controller_test.exs:20: (test)

.

Finished in 13.8 seconds
34 tests, 8 failures

Randomized with seed 268880
[alibaba_html_confirm]$

**Comment by riverrun** [comment]
Thanks for letting me know. I'll look into it and get back to you soon.

**Comment by riverrun** [comment]
Could you update the installer and then try again? I think you are using an old version of the installer.

**Comment by guidotripaldi** [comment]
Sorry David, I don't know why but I've missed your last message, I try now the new installer

**Comment by guidotripaldi** [comment]
All ok now! With new installer the tests run smooth on both html and api projects. Ticket closed.
