### ISSUE TITLE
funny results for get /users/:id

### ISSUE THREAD

**Issue by tnt** [riverrun/phauxth#20]
https://github.com/riverrun/phauxth/blob/44e8f2889602375c1db9051d9b5c2adee85201c1/installer/new/templates/user_controller.ex#L42-L45

Regardless of the url (`/users/1`, `/users/2`,…) it always shows the `current_user` (same for the other actions). Not exactly what I would expect.

Is the stage too early for my expectations?

**Comment by riverrun** [comment]
Thanks for letting me know. I'll fix that now.

**Comment by riverrun** [comment]
Just pushed a fix to the master branch.
