### ISSUE TITLE
id_check not working because 'id' in params refers to resource ID

### ISSUE THREAD

**Issue by mattcree** [riverrun/phauxth#27]
Params contain 'user_id' as my user_id, and 'id' refers to a nested resource in the project I'm working with.

This means I can't use the id_check plug effectively. I'm wondering if there's some way around it. I'm a novice to Phoenix in general, so I'm sure I must be doing something a bit wacky.

The routes look something like this -- http://localhost:4000/users/2/route_details/5

The '2' in this case is (obviously) a user's ID and the '5' is the particular 'route_details' I'm trying to access or delete. My params in this case would look like %{"user_id" => "2", "id" => "5"}

I'm mostly just having issues with deleting things, as the :delete action is one of the things I had going through the :id_check plug. I was tempted to just write a :user_id_check plug, but it seems that this might be considered an issue anyway, so I thought you might be interested to know.

Hopefully this makes some sense. My project isn't very complex -- it's mostly the boilerplate stuff.

**Comment by riverrun** [comment]
You can just edit the id_check plug for your circumstances. The functions in the installer are there to help you get started and provide examples of how you can handle access control.

If you have any further questions, just let me know.

**Comment by mattcree** [comment]
Thanks -- once I had a closer look at where exactly the id_check plug was located, I kinda realised it was something probably intended to be adapted for the particular use. I was able to get it working. 

Thanks so much for the work by the way -- it's very easy to understand and get up and running which really saved me a lot of time (something I haven't got much to waste at the moment!)

**Comment by riverrun** [comment]
Cool!
