### ISSUE TITLE
Phoenix.Router.NoRouteError

### ISSUE THREAD

**Issue by isjaylee** [riverrun/phauxth#46]
When you initially enter invalid user credentials, it redirects you back to /sessions/new. Immediately after, you enter in valid user credentials, you are then redirected to /sessions and receive a no route error.

Steps to reproduce:

1. Create a user (email: "joe@example.com", password: "password")
2. Go to `/sessions/new`
3. Enter invalid credentials (ex: "joe@example.com", password: "foobar")
4. Receive `Invalid credentials` error message
5. Enter valid credentials
6. You are redirected to `/sessions` and receive a `no route found for GET /sessions` error

**Comment by riverrun** [comment]
Thanks for reporting this. I'll have a look and get back to you as soon as possible.

**Comment by riverrun** [comment]
I've made [these changes](https://github.com/riverrun/phauxth-example/commit/c71f1ba143d983290ca0c658697a61a2286ebb96) to the example app (and similar changes to the installer). I think they should solve this issue.

**Comment by isjaylee** [comment]
Awesome, it all works. Installers works as well.
