### ISSUE TITLE
Branch 1.5 Changes - Breaking?

### ISSUE THREAD

**Issue by richjdsmith** [riverrun/phauxth#51]
Hey @riverrun 

Just wondering how the 1.5 branch is coming along? Is it breaking? Just looking to implement Phauxth in a greenfield project and I'm pretty new with Elixir & Phoenix so I'm trying to make sure I am working with stable packages. 

Cheers,

Rich

**Comment by riverrun** [comment]
The 1.5 branch will probably have a few minor breaking changes.

I will probably increase the version number to version 2.0, and I will add an upgrade guide.

I'm a bit busy now, but I hope to be able to release this version some time this month.

I'll add more information to this issue at a later date.

**Comment by riverrun** [comment]
Added an UPGRADE_v2.md guide with information about the changes.
