### ISSUE TITLE
Can't find any backup files when running installer

### ISSUE THREAD

**Issue by antalvarenga** [riverrun/phauxth#55]
I ran the installer with an existing app (mix phauxth.new --confirm --remember) and whether I prompted "y" or "n" when asking if I wanted to overwrite files, I couldn't find any backup files. 
Thank you for Phauxth.

**Comment by dikaio** [comment]
@antalvarenga here's a _few_ of the files that should have been backed up after running that command:

- `router.ex.bak`
- `app.html.eex.bak`

All files that were backed-up will end in **bak**. Are those not there?

**Comment by EmjayFlight** [comment]
@antalvarenga What version of phoenix are you using?

**Comment by antalvarenga** [comment]
{:phoenix, "~> 1.3.0"}

**Comment by EmjayFlight** [comment]
Okay, I recently had an issue where my phoenix version was lower than 1.3 and it would not create the appropriate backup files. When I ran mix phoenix.new --version, I found that my version differed from the mix.exs file and that caused the issue when installing phauxth.

**Comment by antalvarenga** [comment]
I don't think it's that, i ran mix phx.new --version (I used the phx installer) and it returns `Phoenix v1.3.0`

**Comment by antalvarenga** [comment]
Found the issue, I was running an outdated version of the installer. Thanks for the help and sorry for the time I took you!
