### ISSUE TITLE
How to use Phauxth.Token.verify inside connect function of UserSocket

### ISSUE THREAD

**Issue by acrolink** [riverrun/phauxth#56]
I am trying to verify the token inside:

```
  def connect(%{"token" => token}, socket) do
    IO.puts token
    case Phoenix.Token.verify(socket, "user salt", token, max_age: 86400) do
      {:ok, user_id} ->
        IO.puts user_id
        socket = assign(socket, :user, Repo.get!(User, user_id))
        {:ok, socket}
      {:error, _} ->
        IO.puts "error"
        :error
    end
  end
```
But getting errors. How to use `Phauxth.Token.verify` instead of `Phoenix.Token.verify` to verify the `Phauxth `token in this context (channels and sockets)?

**Comment by riverrun** [comment]
The arguments to verify are `key_source, token, max_age, opts`, so in your example, you would write `Phauxth.Token.verify(socket, token, 86400)` (the opts are optional).

**Comment by acrolink** [comment]
Works as designed, I was passing the `max_age `wrongly to the function.
