### ISSUE TITLE
Internationalization

### ISSUE THREAD

**Issue by tmbb** [riverrun/phauxth#58]
Email messages should be internationaized

**Comment by riverrun** [comment]
I'll look into this and get back to you - but it should be no problem.

**Comment by wernerlaude** [comment]
Me to..(new to Phoenix..) can't find a way to translate the messages (login logout etc) using gettext. Can you tell me how?

**Comment by riverrun** [comment]
I'm really busy at the moment, but early June I should be able to address this. Sorry for the delay.

**Comment by riverrun** [comment]
In the latest version of the example app, I have added the email module to the web directory, and I will test it with gettext soon.
