### ISSUE TITLE
Consider providing cookie / session based mechanism for API applications

### ISSUE THREAD

**Issue by acrolink** [riverrun/phauxth#59]
The current behavior of `phauxth` installer is to provide either:

1) Session based authentication if the application is HTML based.
2) Token based authentication if the `api` switch is used.

It would be nice to have additional switch for the installer to specify a JSON API setup based on session / cookie storage (not tokens) since storing the token inside a session cookie provided best security (compared to storing it for example in local storage by the client side JS application).

You are welcome to join the discussion here:
[Sending cookies for stateless SPA authentication using JWT](https://elixirforum.com/t/sending-cookies-for-stateless-spa-authentication-using-jwt/14220)
[](https://elixirforum.com/t/sending-cookies-for-stateless-spa-authentication-using-jwt/14220)

**Comment by vloaix** [comment]
It is not a switch for the installer, but [this](https://hexdocs.pm/phauxth/Phauxth.Authenticate.Base.html#module-authentication-for-use-with-phoenix-channels)?

Also, I think it has made clear that using JWT for client auth is not a good idea in several elixirforum's discussions.

**Comment by riverrun** [comment]
I'm really busy at the moment, but early June I should be able to address this. Sorry for the delay.

**Comment by riverrun** [comment]
I can update the Phauxth Authenticate plug to handle tokens that are stored in cookies. Is that what you want?

**Comment by acrolink** [comment]
@riverrun, I think it would be nice to allow storing and reading the tokens from cookies. I have already done that within Guardian and it is working fine.

**Comment by riverrun** [comment]
I have added information about how to customize Authenticate.Token to the documentation for that module, and there is also an example module in the `custom_authenticate.exs` file (Phauxth.AuthenticateTokenCookie).
