### ISSUE TITLE
Questions regarding 2.0

### ISSUE THREAD

**Issue by dsignr** [riverrun/phauxth#60]
Hi David,
I understand you're pretty busy these days, and just wanted to check with you if 2.0 can be used in production? I know it has a lot of changes under the hood, but just wanted to double check before I use it in any client projects :)

**Comment by riverrun** [comment]
Hi, sorry for the delay in responding :)

I'm using version 2.0 in production where I am working now. There are a couple of things I want to test further, but they relate to customizability, not the basic functionality of the library.

I'll let you know when I release 2.0. I'm hoping it's going to be soon, but that's what I said a few months ago.

**Comment by dsignr** [comment]
Ok, thank you David 👍
