### ISSUE TITLE
Router.Helpers now needs to be explicitly aliased as Routes

### ISSUE THREAD

**Issue by x-ji** [riverrun/phauxth#65]
See https://github.com/phoenixframework/phoenix/commit/928cc6a3713bd64b949a0b102b849a93f1ce344d and https://github.com/phoenixframework/phoenix/issues/2530

When I tried `mix phauxth.new`, code such as `user_path` are generated in views, while it should really be `Routes.user_path` now, after this change in Phoenix.

I'm not sure if this is already addressed in version 2.0 of `phauxth`. A quick search doesn't seem to find any related issue, so I opened this.

**Comment by riverrun** [comment]
Thanks for opening the issue. I'll look into it soon.

**Comment by riverrun** [comment]
Do you know what version this was added?

**Comment by x-ji** [comment]
The changes are still in the master branch and I think in 1.4.0-dev, therefore they are not part of the current 1.3.x versions yet. Guess they'll go into effect when 1.4.0 is officially released.

**Comment by x-ji** [comment]
Also see https://github.com/phoenixframework/phoenix/issues/2955

**Comment by riverrun** [comment]
Thanks. I noticed that they are not in the default installer, so I'm now looking at what the dev installer is producing and updating accordingly.

**Comment by riverrun** [comment]
I have just made some updates to the example app - using the assets folder generated from the dev installer, but I haven't added the Routes alias yet. I want to look into it further and then add it.

**Comment by riverrun** [comment]
I want to wait until Phoenix 1.4 comes out before adding the Routes alias - hopefully, that will be quite soon.

**Comment by riverrun** [comment]
Version 2.0.0 has these changes in the example app - once Phoenix 1.4 and Phauxth 2.0.0 are released, I will update the installer.
