### ISSUE TITLE
Resend confirmation email

### ISSUE THREAD

**Issue by x-ji** [riverrun/phauxth#66]
There doesn't seem to be a built-in solution for resending confirmation emails? Sometimes the email might be lost or end up in spam etc.

**Comment by x-ji** [comment]
Maybe this is already being dealt with in v2?

**Comment by x-ji** [comment]
The user can request password resets but even a successful password reset doesn't seem to confirm the account.

**Comment by riverrun** [comment]
No, there isn't a built-in solution, but I think that it is something that is outside the scope of this library. Your second comment about password reset not checking the confirmation is interesting, and I'll look into that soon.

**Comment by x-ji** [comment]
I mean it's pretty common for websites to provide a "resend confirmation email" link at the log in page, in addition to the "reset password" link, which this library already provides, so I don't think it is that out of scope. I was able to code it up relatively quickly, extending the confirm controller, though it'd be nice if it's already generated in the templates IMO. I can also submit a PR if appropriate.

**Comment by riverrun** [comment]
Could you open an issue at https://github.com/riverrun/phauxth-example ? We can add this feature to the example.
