### ISSUE TITLE
v0.10 installer not working

### ISSUE THREAD

**Issue by hbll** [riverrun/phauxth#7]
I tried to install v0.10 and the installer didn't work. I am getting errors like:
```
[error] beam/beam_load.c(1287): Error loading module 'Elixir.Mix.Tasks.Phauxth.New':
  mandatory chunk of type "Atom" not found
somepath/phauxth_new/ebin/Elixir.Mix.Tasks.Phauxth.New.beam failed: :badfile
```
I'd also like to take the chance to thank you for your great work on comeonin, openmaize, phauxth and other projects.

**Comment by riverrun** [comment]
Thanks for letting me know about this issue.

Could you tell me what version of Elixir and Erlang / Otp you are using?

**Comment by hbll** [comment]
Elixir: 1.4.4
Erlang: 19.3.3(FreeBSD 11)

**Comment by riverrun** [comment]
Could you try installing it locally?

You can do that by clone the repository and then from the installer/new directory, run `MIX_ENV=prod mix archive.build` and `mix archive.install`.

**Comment by hbll** [comment]
I installed it locally, mix couldn't even find any phauxth's tasks. I will try to do a fresh install of erlang from freebsd's ports and report back later.
