### ISSUE TITLE
Phoenix 1.4

### ISSUE THREAD

**Issue by dikaio** [riverrun/phauxth#86]
Any hints on how to get this working with 1.4? From what I can see it's just a matter of updating the paths to prepend with the 1.4 standard way of references with **Routes** e.g. `Routes.auth_path`

**Comment by riverrun** [comment]
I have just updated the [example app](https://github.com/riverrun/phauxth-example) to use version 2.0.0-beta of Phauxth and 1.4.0-rc of Phoenix.

There is also [this guide](https://gist.github.com/chrismccord/bb1f8b136f5a9e4abc0bfc07b832257e) for updating Phoenix apps to 1.4.

Closing this issue for now, but feel free to comment, and if you have any feedback about the changes in version 2.0, please let me know.

**Comment by dikaio** [comment]
Thanks @riverrun!

I think 1.4.0-rc2 forward is going with `{:plug_cowboy, "~> 2.0"},` in place of `{:cowboy, "~> 1.0"}` which is dependent on cowboy 2.5 so wasn't sure if I should have made changes to the example app with a pull request but did want to give you a heads up! Thanks again 👍

**Comment by riverrun** [comment]
Thanks for letting me know. I'll have a look at that myself and get back to you soon.

**Comment by BryanJBryce** [comment]
@dikaio I have a pull request out that fixes all the Route calls in the phauxth-installer repo. https://github.com/riverrun/phauxth_installer/pull/11
