### ISSUE TITLE
Seeds file path incorrect after running `mix phauxth.new`

### ISSUE THREAD

**Issue by florish** [riverrun/phauxth#94]
Hi! I'm just getting started with `phauxth`, using `2.0.0-rc2`.

On running `mix phauxth.new`, I've noticed that the generated `seeds.exs` is oddly placed.

Example steps taken so it can be reproduced (Elixir 1.7.4, Phoenix 1.4.0) :

```
$ mix phx.new phauxth_new
# Default output from phx.new...
$ cd phauxth_new
$ mix archive.install https://github.com/riverrun/phauxth_installer/raw/master/archives/phauxth_new.ez
# Default output...
$ mix phauxth.new
# All kinds of output...
$ tree lib
# (Omitting irrelevant output...)
└── phauxth_newpriv # => incorrect path!
    └── repo
        └── seeds.exs
```

Seems like a `/` is missing in somewhere in the logic to copy over `seeds.exs` to the repository.

As I'm just getting started, I'm not sure how to fix this. I'm therefore bringing it up as an issue. 

With some guidance from the maintainer(s), I'd be more than happy to open up a pull request myself to fix this issue!

**Comment by riverrun** [comment]
Fixed in the latest phauxth_installer
