### ISSUE TITLE
--remember returns error Phauxth.Remember - you need to set a `create_session_func` in the opts

### ISSUE THREAD

**Issue by AndreasBraun2015** [riverrun/phauxth#96]
Thank you for the great package. 

I tried to use the phauxth.new command with --remember. Starting the server returns the following error 

RuntimeError at GET /
Phauxth.Remember - you need to set a `create_session_func` in the opts

I am using phoenix 1.4

**Comment by riverrun** [comment]
Thanks for letting me know.

Could you update the version of the installer that you are using? then it should work fine. Let me know how you get on.

**Comment by AndreasBraun2015** [comment]
With the new version it works fine.
