### ISSUE TITLE
password field does not show up in http://localhost:4000/users/new

### ISSUE THREAD

**Issue by AndreasBraun2015** [riverrun/phauxth#97]
The   <%= if @action == :create do %>  should be probably removed in templates/user/form.html.eex

**Comment by riverrun** [comment]
I think you are using an older version of the installer / example app. If you update to the latest version, it should be working ok.

**Comment by mclosson** [comment]
I also just ran into this issue after creating a new phoenix application and installing the installer, then running the installer like this:

```sh
$ mix archive.install https://github.com/riverrun/phauxth_installer/raw/master/archives/phauxth_new.ez
$ mix phauxth.new --confirm --remember
```

**Comment by riverrun** [comment]
Thanks for letting me know - I've just updated the installer, so it shoudl be working now.

**Comment by AndreasBraun2015** [comment]
Ah I see, I try the updated version, thank you two

**Comment by AndreasBraun2015** [comment]
Works, thank you
